basic/models/Book.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "books".
 *
 * @property int $id
 * @property string $book_name
 * @property string $book_image
 * @property int $book_year
 * @property int $book_status
 * @property int $book_user
 */
class Book extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'books';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['book_name', 'book_year','book_status'], 'required'],
            [['book_year'], 'integer'],
            //[['book_name', 'book_image'], 'max' => 250],
            [['book_image'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'book_name' => 'Book Name',
            'book_image' => 'Book Image',
            'book_year' => 'Book Year',
            'book_status' => 'Book Status',
            'book_user' => 'Book User',
        ];
    }

    public function upload()
    {
        if ($this->validate()) {
           // var_dump(Yii::getAlias('@webroot'));die;
            $this->book_image->saveAs(Yii::getAlias('@webroot').'/uploads/' . $this->book_image->baseName . '.' . $this->book_image->extension);
            return true;
        } else {

            return false;
        }
    }

    public static function changeBookStatus()
    {
        return array(0=>'public',1=>'protected',2=>'private');
    }

    public function getNameBookStatus($status)
    {
        return Books::changeBookStatus()[$status];
        //return $temp[$this->book_status];
    }

}

basic/controllers/BookController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Book;
use app\models\BookSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BookController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['view'],
                'rules' => [
                    [
                        'actions' => ['view'],
                        'allow' => true,
                        'roles' => ['?'],
                        'matchCallback' =>$this->allowPermission(),
                        'denyCallback' => function ($rule, $action){return $this->goHome();},

                    ],

                ],
            ],
        ];
    }


    public function allowPermission()
    {
        if(isset($_GET["id"])) {
            $model = $this->findModel($_GET["id"]);
           // var_dump(Yii::$app->user->isGuest && $model->book_status != 0);die;
            if (Yii::$app->user->isGuest && $model->book_status != 0) {
                return false;
            }
            if (!Yii::$app->user->isGuest) {
                // $model = $this->findModel($_GET["id"]);
                //var_dump($model->book_status == 2 && $model->book_user != Yii::$app->user->id);die;
                return !($model->book_status == 2 && $model->book_user != Yii::$app->user->id);
            }
        }
    }
    /**
     * Lists all Book models.
     * @return mixed
     */

    public function actionIndex()
    {
        $searchModel = new BookSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        //var_dump(Yii::$app->request->queryParams);die;
        $dataProvider->pagination->defaultPageSize=2;
//        $dataProvider->query->andWhere(['book_status' => 0] );
//        if (!Yii::$app->user->isGuest)
//        {
//            $user_id = Yii::$app->user->id;
//            $dataProvider->query->orWhere(['book_status'=> 1]);
//            $dataProvider->query->orWhere(['and',['book_status'=> 2],['book_user'=>$user_id]]);
//
//        }
       // print_r($dataProvider->query);exit;
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }


    function actionDownload(){


        $book_id = $_GET['id'] ;
        $model = $this->findModel($book_id);
        $image = $model->book_image;
//        $book_status = $_GET['book_status'] ;
//        if($book_status==2 && $user_id!=Yii::app()->user->id )
//        {
//            return;
//        }

//	    var_dump($name);
        $filecontent=file_get_contents(Yii::getAlias('@webroot').'/uploads/'.$image);
        header("Content-Type: text/plain");
        header("Content-disposition: attachment; filename=$image");
        header("Pragma: no-cache");
        echo $filecontent;
        exit;
    }

    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Book();

        if ($model->load(Yii::$app->request->post())) {
            //var_dump(UploadedFile::getInstance($model, 'book_image'));die;
            $model->book_image = UploadedFile::getInstance($model, 'book_image');
            $model->book_user = Yii::$app->user->id;
           // var_dump($model->book_status);die;
            if ($model->save()) {
                if($model->upload()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
                else
                {
                    var_dump('bien');die;
                }

            }

        } else {

            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

basic/views/book/_form.php
<?php

use yii\helpers\Html;
use app\models\Book;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Book */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'book_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'book_image')->fileInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'book_year')->textInput() ?>

    <?= $form->field($model,'book_status')->dropDownList(Book::changeBookStatus()) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/book/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BookSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-search pull-right">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => ['class' => 'form-inline'],
    ]); ?>
    <div class="form-group">
         <?= $form->field($model, 'book_name',
                        ['inputOptions'=> ['class'=>'form-control input-md']])->textInput(['placeholder'=>'Search']); ?>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/book/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Book */

$this->title = 'Create Book';
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/book/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models;
use app\models\Book;
use app\models\BookSearch;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BookSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Book';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Book', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'book_name',
            [
                'attribute' => 'book_image',
                'format' => 'html',
                'label' => 'Book_image',
                'value' => function ($data) {
                    return Html::img(Yii::$app->request->BaseUrl.'/uploads/' . $data->book_image,
                        ['width' => '60px']);
                },
            ],
            'book_year',
            [
                    'class' => 'yii\grid\DataColumn',
                    'value' => function($data){
                        $book = new Book($data);
//                        return $data->getNameBookStatus($data->book_status);
//                        return $data->getNameBookStatus();
                        //return $book->getNameBookStatus($book->book_status);
                    }
            ],
            ['class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'download' => function ($url, $model, $key) {
                        return Html::a ( '<span class="glyphicon glyphicon-download"></span> ', ['book/download', 'id' => $model->id] );
                    },
                ],
                'template' => '{update} {view} {delete} {download}'
            ],
        ],
    ]); ?>
</div>

basic/views/book/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Book */

$this->title = 'Update Book: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="book-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/book/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\Book;

/* @var $this yii\web\View */
/* @var $model app\models\Book */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'book_name',
            [
                'attribute' => 'book_image',
                'format' => 'html',
                'label' => 'Book Image',
                'value' => function ($model) {
                    return Html::img(Yii::$app->request->BaseUrl.'/uploads/' . $model->book_image,
                        ['width' => '60px']);
                },
            ],
            'book_year',
//            [                      // the owner name of the model
//                'label' => 'Book status',
//                'value' => $model->getNameBookStatus($model->book_status),
//            ],

        ],
    ]) ?>

</div>